// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	ListEntriesRequest
	GetEntryRequest
	CreateEntryRequest
	UpdateEntryRequest
	EntryList
	ListEntryCommentsRequest
	CommentList
	Entry
	Author
	CreateEntryCommentRequest
	UpdateEntryCommentRequest
	Comment
	Tag
	JWT
	AuthURL
	ActivityList
	Activity
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Activity_Action int32

const (
	Activity_CREATE_ENTRY Activity_Action = 0
	Activity_UPDATE_ENTRY Activity_Action = 1
)

var Activity_Action_name = map[int32]string{
	0: "CREATE_ENTRY",
	1: "UPDATE_ENTRY",
}
var Activity_Action_value = map[string]int32{
	"CREATE_ENTRY": 0,
	"UPDATE_ENTRY": 1,
}

func (x Activity_Action) String() string {
	return proto.EnumName(Activity_Action_name, int32(x))
}
func (Activity_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{16, 0} }

type ListEntriesRequest struct {
	Page       int64  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	NumPerPage int64  `protobuf:"varint,2,opt,name=num_per_page,json=numPerPage" json:"num_per_page,omitempty"`
	Keyword    string `protobuf:"bytes,3,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *ListEntriesRequest) Reset()                    { *m = ListEntriesRequest{} }
func (m *ListEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListEntriesRequest) ProtoMessage()               {}
func (*ListEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListEntriesRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListEntriesRequest) GetNumPerPage() int64 {
	if m != nil {
		return m.NumPerPage
	}
	return 0
}

func (m *ListEntriesRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type GetEntryRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEntryRequest) Reset()                    { *m = GetEntryRequest{} }
func (m *GetEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntryRequest) ProtoMessage()               {}
func (*GetEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetEntryRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateEntryRequest struct {
	Title    string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	AuthorId int64    `protobuf:"varint,4,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	TagIds   []string `protobuf:"bytes,5,rep,name=tag_ids,json=tagIds" json:"tag_ids,omitempty"`
}

func (m *CreateEntryRequest) Reset()                    { *m = CreateEntryRequest{} }
func (m *CreateEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEntryRequest) ProtoMessage()               {}
func (*CreateEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateEntryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateEntryRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateEntryRequest) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *CreateEntryRequest) GetTagIds() []string {
	if m != nil {
		return m.TagIds
	}
	return nil
}

type UpdateEntryRequest struct {
	Id      int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TagIds  []string `protobuf:"bytes,4,rep,name=tag_ids,json=tagIds" json:"tag_ids,omitempty"`
}

func (m *UpdateEntryRequest) Reset()                    { *m = UpdateEntryRequest{} }
func (m *UpdateEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntryRequest) ProtoMessage()               {}
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateEntryRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateEntryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateEntryRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateEntryRequest) GetTagIds() []string {
	if m != nil {
		return m.TagIds
	}
	return nil
}

type EntryList struct {
	Entries    []*Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	NumResults int64    `protobuf:"varint,2,opt,name=num_results,json=numResults" json:"num_results,omitempty"`
}

func (m *EntryList) Reset()                    { *m = EntryList{} }
func (m *EntryList) String() string            { return proto.CompactTextString(m) }
func (*EntryList) ProtoMessage()               {}
func (*EntryList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EntryList) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *EntryList) GetNumResults() int64 {
	if m != nil {
		return m.NumResults
	}
	return 0
}

type ListEntryCommentsRequest struct {
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
}

func (m *ListEntryCommentsRequest) Reset()                    { *m = ListEntryCommentsRequest{} }
func (m *ListEntryCommentsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListEntryCommentsRequest) ProtoMessage()               {}
func (*ListEntryCommentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListEntryCommentsRequest) GetEntryId() string {
	if m != nil {
		return m.EntryId
	}
	return ""
}

type CommentList struct {
	Comments []*Comment `protobuf:"bytes,1,rep,name=comments" json:"comments,omitempty"`
}

func (m *CommentList) Reset()                    { *m = CommentList{} }
func (m *CommentList) String() string            { return proto.CompactTextString(m) }
func (*CommentList) ProtoMessage()               {}
func (*CommentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CommentList) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Entry struct {
	Id          int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content     string  `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Author      *Author `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Tags        []*Tag  `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	CreatedDate string  `protobuf:"bytes,6,opt,name=created_date,json=createdDate" json:"created_date,omitempty"`
	UpdatedDate string  `protobuf:"bytes,7,opt,name=updated_date,json=updatedDate" json:"updated_date,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Entry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entry) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Entry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Entry) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Entry) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Entry) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Entry) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

type Author struct {
	Id            int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sub           string `protobuf:"bytes,2,opt,name=sub" json:"sub,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	GivenName     string `protobuf:"bytes,4,opt,name=given_name,json=givenName" json:"given_name,omitempty"`
	FamilyName    string `protobuf:"bytes,5,opt,name=family_name,json=familyName" json:"family_name,omitempty"`
	Profile       string `protobuf:"bytes,6,opt,name=profile" json:"profile,omitempty"`
	Picture       string `protobuf:"bytes,7,opt,name=picture" json:"picture,omitempty"`
	Email         string `protobuf:"bytes,8,opt,name=email" json:"email,omitempty"`
	EmailVerified string `protobuf:"bytes,9,opt,name=email_verified,json=emailVerified" json:"email_verified,omitempty"`
	Gender        string `protobuf:"bytes,10,opt,name=gender" json:"gender,omitempty"`
}

func (m *Author) Reset()                    { *m = Author{} }
func (m *Author) String() string            { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()               {}
func (*Author) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Author) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Author) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Author) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Author) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Author) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Author) GetEmailVerified() string {
	if m != nil {
		return m.EmailVerified
	}
	return ""
}

func (m *Author) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type CreateEntryCommentRequest struct {
	EntryId  string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	AuthorId string `protobuf:"bytes,2,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *CreateEntryCommentRequest) Reset()                    { *m = CreateEntryCommentRequest{} }
func (m *CreateEntryCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEntryCommentRequest) ProtoMessage()               {}
func (*CreateEntryCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateEntryCommentRequest) GetEntryId() string {
	if m != nil {
		return m.EntryId
	}
	return ""
}

func (m *CreateEntryCommentRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *CreateEntryCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateEntryCommentRequest struct {
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *UpdateEntryCommentRequest) Reset()                    { *m = UpdateEntryCommentRequest{} }
func (m *UpdateEntryCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntryCommentRequest) ProtoMessage()               {}
func (*UpdateEntryCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateEntryCommentRequest) GetEntryId() string {
	if m != nil {
		return m.EntryId
	}
	return ""
}

func (m *UpdateEntryCommentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateEntryCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Comment struct {
	Id          int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content     string  `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Author      *Author `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	CreatedDate string  `protobuf:"bytes,4,opt,name=created_date,json=createdDate" json:"created_date,omitempty"`
	UpdatedDate string  `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate" json:"updated_date,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Comment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Comment) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Comment) GetUpdatedDate() string {
	if m != nil {
		return m.UpdatedDate
	}
	return ""
}

type Tag struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type JWT struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (m *JWT) Reset()                    { *m = JWT{} }
func (m *JWT) String() string            { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()               {}
func (*JWT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *JWT) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthURL struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *AuthURL) Reset()                    { *m = AuthURL{} }
func (m *AuthURL) String() string            { return proto.CompactTextString(m) }
func (*AuthURL) ProtoMessage()               {}
func (*AuthURL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AuthURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ActivityList struct {
	Activities []*Activity `protobuf:"bytes,1,rep,name=activities" json:"activities,omitempty"`
	NumResults int64       `protobuf:"varint,2,opt,name=num_results,json=numResults" json:"num_results,omitempty"`
}

func (m *ActivityList) Reset()                    { *m = ActivityList{} }
func (m *ActivityList) String() string            { return proto.CompactTextString(m) }
func (*ActivityList) ProtoMessage()               {}
func (*ActivityList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ActivityList) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *ActivityList) GetNumResults() int64 {
	if m != nil {
		return m.NumResults
	}
	return 0
}

type Activity struct {
	Id          string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action      Activity_Action `protobuf:"varint,2,opt,name=action,enum=rpc.Activity_Action" json:"action,omitempty"`
	Description string          `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Author      *Author         `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	URI         string          `protobuf:"bytes,5,opt,name=URI" json:"URI,omitempty"`
}

func (m *Activity) Reset()                    { *m = Activity{} }
func (m *Activity) String() string            { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()               {}
func (*Activity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Activity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Activity) GetAction() Activity_Action {
	if m != nil {
		return m.Action
	}
	return Activity_CREATE_ENTRY
}

func (m *Activity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Activity) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Activity) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func init() {
	proto.RegisterType((*ListEntriesRequest)(nil), "rpc.ListEntriesRequest")
	proto.RegisterType((*GetEntryRequest)(nil), "rpc.GetEntryRequest")
	proto.RegisterType((*CreateEntryRequest)(nil), "rpc.CreateEntryRequest")
	proto.RegisterType((*UpdateEntryRequest)(nil), "rpc.UpdateEntryRequest")
	proto.RegisterType((*EntryList)(nil), "rpc.EntryList")
	proto.RegisterType((*ListEntryCommentsRequest)(nil), "rpc.ListEntryCommentsRequest")
	proto.RegisterType((*CommentList)(nil), "rpc.CommentList")
	proto.RegisterType((*Entry)(nil), "rpc.Entry")
	proto.RegisterType((*Author)(nil), "rpc.Author")
	proto.RegisterType((*CreateEntryCommentRequest)(nil), "rpc.CreateEntryCommentRequest")
	proto.RegisterType((*UpdateEntryCommentRequest)(nil), "rpc.UpdateEntryCommentRequest")
	proto.RegisterType((*Comment)(nil), "rpc.Comment")
	proto.RegisterType((*Tag)(nil), "rpc.Tag")
	proto.RegisterType((*JWT)(nil), "rpc.JWT")
	proto.RegisterType((*AuthURL)(nil), "rpc.AuthURL")
	proto.RegisterType((*ActivityList)(nil), "rpc.ActivityList")
	proto.RegisterType((*Activity)(nil), "rpc.Activity")
	proto.RegisterEnum("rpc.Activity_Action", Activity_Action_name, Activity_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KobService service

type KobServiceClient interface {
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*EntryList, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*Entry, error)
	CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*Entry, error)
	UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*Entry, error)
	ListEntryComments(ctx context.Context, in *ListEntryCommentsRequest, opts ...grpc.CallOption) (*CommentList, error)
	CreateEntryComment(ctx context.Context, in *CreateEntryCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	UpdateEntryComment(ctx context.Context, in *UpdateEntryCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	CreateJWT(ctx context.Context, in *Author, opts ...grpc.CallOption) (*JWT, error)
	CreateAuthURL(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AuthURL, error)
	ListActivity(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ActivityList, error)
}

type kobServiceClient struct {
	cc *grpc.ClientConn
}

func NewKobServiceClient(cc *grpc.ClientConn) KobServiceClient {
	return &kobServiceClient{cc}
}

func (c *kobServiceClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*EntryList, error) {
	out := new(EntryList)
	err := grpc.Invoke(ctx, "/rpc.KobService/ListEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := grpc.Invoke(ctx, "/rpc.KobService/GetEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := grpc.Invoke(ctx, "/rpc.KobService/CreateEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) UpdateEntry(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := grpc.Invoke(ctx, "/rpc.KobService/UpdateEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) ListEntryComments(ctx context.Context, in *ListEntryCommentsRequest, opts ...grpc.CallOption) (*CommentList, error) {
	out := new(CommentList)
	err := grpc.Invoke(ctx, "/rpc.KobService/ListEntryComments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) CreateEntryComment(ctx context.Context, in *CreateEntryCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := grpc.Invoke(ctx, "/rpc.KobService/CreateEntryComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) UpdateEntryComment(ctx context.Context, in *UpdateEntryCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := grpc.Invoke(ctx, "/rpc.KobService/UpdateEntryComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) CreateJWT(ctx context.Context, in *Author, opts ...grpc.CallOption) (*JWT, error) {
	out := new(JWT)
	err := grpc.Invoke(ctx, "/rpc.KobService/CreateJWT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) CreateAuthURL(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AuthURL, error) {
	out := new(AuthURL)
	err := grpc.Invoke(ctx, "/rpc.KobService/CreateAuthURL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobServiceClient) ListActivity(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ActivityList, error) {
	out := new(ActivityList)
	err := grpc.Invoke(ctx, "/rpc.KobService/ListActivity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KobService service

type KobServiceServer interface {
	ListEntries(context.Context, *ListEntriesRequest) (*EntryList, error)
	GetEntry(context.Context, *GetEntryRequest) (*Entry, error)
	CreateEntry(context.Context, *CreateEntryRequest) (*Entry, error)
	UpdateEntry(context.Context, *UpdateEntryRequest) (*Entry, error)
	ListEntryComments(context.Context, *ListEntryCommentsRequest) (*CommentList, error)
	CreateEntryComment(context.Context, *CreateEntryCommentRequest) (*Comment, error)
	UpdateEntryComment(context.Context, *UpdateEntryCommentRequest) (*Comment, error)
	CreateJWT(context.Context, *Author) (*JWT, error)
	CreateAuthURL(context.Context, *google_protobuf1.Empty) (*AuthURL, error)
	ListActivity(context.Context, *google_protobuf1.Empty) (*ActivityList, error)
}

func RegisterKobServiceServer(s *grpc.Server, srv KobServiceServer) {
	s.RegisterService(&_KobService_serviceDesc, srv)
}

func _KobService_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/ListEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).ListEntries(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_CreateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).CreateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/CreateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).CreateEntry(ctx, req.(*CreateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_UpdateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).UpdateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/UpdateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).UpdateEntry(ctx, req.(*UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_ListEntryComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntryCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).ListEntryComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/ListEntryComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).ListEntryComments(ctx, req.(*ListEntryCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_CreateEntryComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).CreateEntryComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/CreateEntryComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).CreateEntryComment(ctx, req.(*CreateEntryCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_UpdateEntryComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).UpdateEntryComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/UpdateEntryComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).UpdateEntryComment(ctx, req.(*UpdateEntryCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_CreateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Author)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).CreateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/CreateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).CreateJWT(ctx, req.(*Author))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_CreateAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).CreateAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/CreateAuthURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).CreateAuthURL(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobService_ListActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobServiceServer).ListActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KobService/ListActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobServiceServer).ListActivity(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _KobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.KobService",
	HandlerType: (*KobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEntries",
			Handler:    _KobService_ListEntries_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _KobService_GetEntry_Handler,
		},
		{
			MethodName: "CreateEntry",
			Handler:    _KobService_CreateEntry_Handler,
		},
		{
			MethodName: "UpdateEntry",
			Handler:    _KobService_UpdateEntry_Handler,
		},
		{
			MethodName: "ListEntryComments",
			Handler:    _KobService_ListEntryComments_Handler,
		},
		{
			MethodName: "CreateEntryComment",
			Handler:    _KobService_CreateEntryComment_Handler,
		},
		{
			MethodName: "UpdateEntryComment",
			Handler:    _KobService_UpdateEntryComment_Handler,
		},
		{
			MethodName: "CreateJWT",
			Handler:    _KobService_CreateJWT_Handler,
		},
		{
			MethodName: "CreateAuthURL",
			Handler:    _KobService_CreateAuthURL_Handler,
		},
		{
			MethodName: "ListActivity",
			Handler:    _KobService_ListActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0x3f, 0xb1, 0xbd, 0x67, 0x9d, 0xd4, 0x1d, 0x85, 0x66, 0xb3, 0x69, 0xa8, 0x3b, 0x10,
	0xc9, 0x6a, 0x4b, 0x0c, 0x41, 0x08, 0x89, 0x0b, 0xa4, 0x28, 0x8d, 0x20, 0x25, 0x94, 0xb0, 0x75,
	0xa8, 0xb8, 0xc1, 0x6c, 0x76, 0x27, 0xcb, 0xa8, 0xfb, 0xc7, 0xee, 0x6c, 0x90, 0x41, 0xbd, 0x81,
	0x0b, 0x1e, 0x80, 0x7b, 0x5e, 0x09, 0x24, 0x5e, 0x81, 0x07, 0x41, 0x73, 0x66, 0x36, 0xd9, 0xb5,
	0x6b, 0xb9, 0x88, 0xbb, 0x39, 0x3f, 0x73, 0xbe, 0x33, 0xe7, 0x77, 0xc0, 0xc8, 0x52, 0x6f, 0x3f,
	0xcd, 0x12, 0x91, 0x90, 0x56, 0x96, 0x7a, 0xf6, 0xdd, 0x20, 0x49, 0x82, 0x90, 0x8d, 0xdd, 0x94,
	0x8f, 0xdd, 0x38, 0x4e, 0x84, 0x2b, 0x78, 0x12, 0xe7, 0x4a, 0xc5, 0xde, 0xd1, 0x52, 0xa4, 0x2e,
	0x8a, 0xcb, 0x31, 0x8b, 0x52, 0x31, 0x53, 0x42, 0xea, 0x03, 0x39, 0xe5, 0xb9, 0x38, 0x8e, 0x45,
	0xc6, 0x59, 0xee, 0xb0, 0x1f, 0x0a, 0x96, 0x0b, 0x42, 0xa0, 0x9d, 0xba, 0x01, 0xb3, 0x1a, 0xc3,
	0xc6, 0xa8, 0xe5, 0xe0, 0x99, 0x0c, 0xa1, 0x1f, 0x17, 0xd1, 0x34, 0x65, 0xd9, 0x14, 0x65, 0x4d,
	0x94, 0x41, 0x5c, 0x44, 0x67, 0x2c, 0x3b, 0x93, 0x1a, 0x16, 0x74, 0x5f, 0xb0, 0xd9, 0x8f, 0x49,
	0xe6, 0x5b, 0xad, 0x61, 0x63, 0x64, 0x38, 0x25, 0x49, 0xef, 0xc3, 0xad, 0x4f, 0x19, 0x82, 0xcc,
	0x4a, 0x88, 0x0d, 0x68, 0x72, 0x5f, 0x03, 0x34, 0xb9, 0x4f, 0x7f, 0x02, 0x72, 0x94, 0x31, 0x57,
	0xb0, 0x9a, 0xd6, 0x26, 0xac, 0x09, 0x2e, 0x42, 0x85, 0x66, 0x38, 0x8a, 0x90, 0x40, 0x5e, 0x12,
	0x0b, 0x16, 0x8b, 0x12, 0x48, 0x93, 0x64, 0x07, 0x0c, 0xb7, 0x10, 0xdf, 0x27, 0xd9, 0x94, 0xfb,
	0x56, 0x1b, 0x8d, 0xf7, 0x14, 0xe3, 0xc4, 0x27, 0x5b, 0xd0, 0x15, 0x6e, 0x30, 0xe5, 0x7e, 0x6e,
	0xad, 0x0d, 0x5b, 0x23, 0xc3, 0xe9, 0x08, 0x37, 0x38, 0xf1, 0x73, 0x1a, 0x01, 0x39, 0x4f, 0xfd,
	0x79, 0xec, 0x39, 0x0f, 0xff, 0xb3, 0x2f, 0x15, 0xb8, 0x76, 0x0d, 0xce, 0x01, 0x03, 0x81, 0x64,
	0xe0, 0xc9, 0x3b, 0xd0, 0x65, 0x2a, 0xf8, 0x56, 0x63, 0xd8, 0x1a, 0x99, 0x07, 0xb0, 0x2f, 0xb3,
	0xab, 0x3c, 0x29, 0x45, 0xe4, 0x1e, 0x98, 0x32, 0xf8, 0x19, 0xcb, 0x8b, 0x50, 0xe4, 0x95, 0xd8,
	0x3b, 0x8a, 0x43, 0x3f, 0x04, 0xab, 0xcc, 0xe3, 0xec, 0x28, 0x89, 0x22, 0x16, 0x8b, 0xeb, 0x6c,
	0x6e, 0x43, 0x4f, 0xda, 0x99, 0x4d, 0xf5, 0x73, 0x0c, 0x65, 0x77, 0x76, 0xe2, 0xd3, 0x8f, 0xc0,
	0xd4, 0xda, 0xe8, 0xcc, 0x08, 0x7a, 0x9e, 0xbe, 0xac, 0xbd, 0xe9, 0xa3, 0x37, 0x5a, 0xc7, 0xb9,
	0x96, 0xd2, 0xbf, 0x1a, 0xb0, 0x86, 0x60, 0xff, 0x3b, 0x4c, 0x6f, 0x43, 0x47, 0x65, 0x08, 0xf3,
	0x65, 0x1e, 0x98, 0x88, 0x78, 0x88, 0x2c, 0x47, 0x8b, 0xc8, 0x5d, 0x68, 0x0b, 0x37, 0x50, 0x79,
	0x33, 0x0f, 0x7a, 0xa8, 0x32, 0x71, 0x03, 0x07, 0xb9, 0xe4, 0x3e, 0xf4, 0x3d, 0xac, 0x1d, 0x7f,
	0x2a, 0xb3, 0x68, 0x75, 0x10, 0xc1, 0xd4, 0xbc, 0xc7, 0xae, 0x60, 0x52, 0xa5, 0xc0, 0x14, 0x6b,
	0x95, 0xae, 0x52, 0xd1, 0x3c, 0xa9, 0x42, 0x7f, 0x6b, 0x42, 0x47, 0xc1, 0x2e, 0xbc, 0x69, 0x00,
	0xad, 0xbc, 0xb8, 0xd0, 0x2f, 0x92, 0x47, 0xd9, 0x21, 0xb1, 0x1b, 0x31, 0xfd, 0x18, 0x3c, 0x93,
	0x5d, 0x80, 0x80, 0x5f, 0xb1, 0x78, 0x8a, 0x92, 0x36, 0x4a, 0x0c, 0xe4, 0x3c, 0x95, 0xe2, 0x7b,
	0x60, 0x5e, 0xba, 0x11, 0x0f, 0x67, 0x4a, 0xbe, 0x86, 0x72, 0x50, 0x2c, 0x54, 0xb0, 0xa0, 0x9b,
	0x66, 0xc9, 0x25, 0x0f, 0xcb, 0x17, 0x94, 0x24, 0x4a, 0xb8, 0x27, 0x8a, 0xac, 0x74, 0xbc, 0x24,
	0x65, 0xb4, 0x59, 0xe4, 0xf2, 0xd0, 0xea, 0xa9, 0x68, 0x23, 0x41, 0xf6, 0x60, 0x03, 0x0f, 0xd3,
	0x2b, 0x96, 0xf1, 0x4b, 0xce, 0x7c, 0xcb, 0x40, 0xf1, 0x3a, 0x72, 0xbf, 0xd6, 0x4c, 0x72, 0x07,
	0x3a, 0x01, 0x8b, 0x7d, 0x96, 0x59, 0x80, 0x62, 0x4d, 0xd1, 0x08, 0xb6, 0x2b, 0xbd, 0x58, 0x26,
	0x7f, 0x65, 0x35, 0xd5, 0xbb, 0x4f, 0x05, 0xeb, 0xa6, 0xfb, 0x96, 0x56, 0x00, 0xfd, 0x0e, 0xb6,
	0x2b, 0xed, 0xf7, 0xfa, 0x70, 0x2a, 0x4b, 0x0a, 0x47, 0x66, 0x69, 0x39, 0xc2, 0x1f, 0x0d, 0xe8,
	0x6a, 0xbb, 0x0b, 0xb9, 0xad, 0xdc, 0x6a, 0x2e, 0xab, 0xcc, 0xd6, 0xf2, 0xca, 0x9c, 0xaf, 0xbd,
	0xf6, 0xea, 0xda, 0x5b, 0x5b, 0xac, 0xbd, 0x87, 0xd0, 0x9a, 0xb8, 0xc1, 0xab, 0x7a, 0x29, 0x74,
	0x2f, 0x58, 0x58, 0xf6, 0x12, 0x12, 0x74, 0x1b, 0x5a, 0x4f, 0x9e, 0x4f, 0x64, 0x09, 0x7a, 0x89,
	0xcf, 0x74, 0x54, 0xf0, 0x4c, 0x77, 0xa0, 0x2b, 0xfd, 0x3b, 0x77, 0x4e, 0x65, 0xcd, 0x16, 0x59,
	0xa8, 0xa5, 0xf2, 0x48, 0xbf, 0x85, 0xfe, 0xa1, 0x27, 0xf8, 0x15, 0x17, 0x6a, 0xf4, 0xbc, 0x0b,
	0xe0, 0x2a, 0xfa, 0x66, 0xfa, 0xac, 0xab, 0x37, 0x6a, 0x35, 0xa7, 0xa2, 0xb0, 0x7a, 0x06, 0xfd,
	0xd9, 0x80, 0x5e, 0x79, 0xb3, 0xf2, 0x14, 0x95, 0x9c, 0x47, 0xd0, 0x91, 0xb6, 0x92, 0x18, 0x2f,
	0x6e, 0x1c, 0x6c, 0xd6, 0x80, 0xf0, 0x90, 0xc4, 0x8e, 0xd6, 0x21, 0x43, 0x30, 0x7d, 0x96, 0x7b,
	0x19, 0x4f, 0xf1, 0x8a, 0x4a, 0x67, 0x95, 0xf5, 0x7a, 0x63, 0x63, 0x00, 0xad, 0x73, 0xe7, 0x44,
	0x07, 0x5c, 0x1e, 0xe9, 0x23, 0xe8, 0x28, 0x28, 0x32, 0x80, 0xfe, 0x91, 0x73, 0x7c, 0x38, 0x39,
	0x9e, 0x1e, 0x3f, 0x9d, 0x38, 0xdf, 0x0c, 0xde, 0x90, 0x9c, 0xf3, 0xb3, 0xc7, 0x37, 0x9c, 0xc6,
	0xc1, 0xaf, 0x5d, 0x80, 0xcf, 0x93, 0x8b, 0x67, 0x2c, 0xbb, 0xe2, 0x1e, 0x23, 0x5f, 0x80, 0x59,
	0x59, 0x96, 0x64, 0x0b, 0x21, 0x17, 0xd7, 0xa7, 0xbd, 0x71, 0x33, 0xc2, 0xa5, 0x94, 0xbe, 0xf9,
	0xcb, 0xdf, 0xff, 0xfc, 0xde, 0xbc, 0x45, 0xd6, 0x71, 0x43, 0x5f, 0xbd, 0x3f, 0xc6, 0x0a, 0x26,
	0x9f, 0x41, 0xaf, 0xdc, 0x8a, 0x44, 0x85, 0x63, 0x6e, 0x49, 0xda, 0x95, 0x5d, 0x40, 0x6d, 0x34,
	0xb2, 0x49, 0x48, 0xcd, 0xc8, 0xf8, 0x67, 0xee, 0xbf, 0x24, 0xa7, 0x60, 0x56, 0x1a, 0x56, 0x3b,
	0xb6, 0xb8, 0x4e, 0x6b, 0xf6, 0x2c, 0xb4, 0x47, 0x68, 0xdd, 0xa9, 0x8f, 0x1b, 0x0f, 0xc8, 0x57,
	0x60, 0x56, 0xfa, 0x51, 0x5b, 0x5b, 0x5c, 0x90, 0x35, 0x6b, 0xbb, 0x68, 0x6d, 0xcb, 0x7e, 0x85,
	0x77, 0xd2, 0x64, 0x0c, 0xb7, 0x17, 0xd6, 0x13, 0xd9, 0xad, 0xc5, 0x6f, 0x7e, 0x6d, 0xd9, 0x83,
	0xea, 0xea, 0xc1, 0x38, 0x8e, 0x10, 0x84, 0x92, 0xe1, 0x1c, 0x48, 0x39, 0x20, 0x5e, 0x8e, 0xf5,
	0x7e, 0x22, 0x49, 0xed, 0x37, 0x51, 0xb6, 0xfe, 0x5b, 0xf3, 0x71, 0xa9, 0xcf, 0x1a, 0xbb, 0xb6,
	0xec, 0xe8, 0x43, 0x44, 0xdb, 0xa3, 0x2b, 0xd1, 0xe4, 0x03, 0x45, 0xed, 0x0b, 0x51, 0x07, 0x5c,
	0x3a, 0xdc, 0xe6, 0x00, 0xdf, 0x43, 0xc0, 0x07, 0xf6, 0xde, 0x2a, 0xc0, 0xeb, 0xb0, 0x7e, 0x02,
	0x86, 0x7a, 0x8d, 0x9c, 0x07, 0xd5, 0x0e, 0xb0, 0xd5, 0x8a, 0x7c, 0xf2, 0x7c, 0xb2, 0x58, 0x37,
	0xb2, 0x37, 0xc6, 0x22, 0x79, 0xc1, 0x62, 0xf2, 0x25, 0xac, 0xab, 0xfb, 0xe5, 0xd0, 0xb8, 0xb3,
	0xaf, 0x3e, 0x8b, 0xfb, 0xe5, 0x67, 0x71, 0xff, 0x58, 0x7e, 0x16, 0xb5, 0xa3, 0x5a, 0xab, 0x2c,
	0x1d, 0x32, 0xa8, 0x99, 0x2c, 0xb2, 0x90, 0x3c, 0x83, 0xbe, 0xcc, 0xd4, 0xf5, 0x14, 0x58, 0x66,
	0xef, 0x76, 0xad, 0xfb, 0x31, 0xb9, 0x8b, 0x46, 0xb5, 0xf4, 0xa2, 0x83, 0x97, 0x3f, 0xf8, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x70, 0x8a, 0x45, 0xf7, 0x0a, 0x00, 0x00,
}
