version: "3"
services:
  kob-db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kob}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insecure}